export const environment = {
    countryList: [
        { name: "Afghanistan", value: 1, isSelected: false },
        { name: "Albania", value: 2, isSelected: false },
        { name: "Algeria", value: 3, isSelected: false },
        { name: "American Samoa", value: 4, isSelected: false },
        { name: "Andorra", value: 5, isSelected: false },
        { name: "Angola", value: 6, isSelected: false },
        { name: "Anguilla", value: 7, isSelected: false },
        { name: "Antarctica", value: 8, isSelected: false },
        { name: "Antigua and Barbuda", value: 9, isSelected: false },
        { name: "Argentina", value: 10, isSelected: false },
        { name: "Armenia", value: 11, isSelected: false },
        { name: "Aruba", value: 12, isSelected: false },
        { name: "Australia", value: 13, isSelected: false },
        { name: "Austria", value: 14, isSelected: false },
        { name: "Azerbaijan", value: 15, isSelected: false },
        { name: "Bahamas (the)", value: 16, isSelected: false },
        { name: "Bahrain", value: 17, isSelected: false },
        { name: "Bangladesh", value: 18, isSelected: false },
        { name: "Barbados", value: 19, isSelected: false },
        { name: "Belarus", value: 20, isSelected: false },
        { name: "Belgium", value: 21, isSelected: false },
        { name: "Belize", value: 22, isSelected: false },
        { name: "Benin", value: 23, isSelected: false },
        { name: "Bermuda", value: 24, isSelected: false },
        { name: "Bhutan", value: 25, isSelected: false },
        { name: "Bolivia (Plurinational State of)", value: 26, isSelected: false },
        { name: "Bonaire, Sint Eustatius and Saba", value: 27, isSelected: false },
        { name: "Bosnia and Herzegovina", value: 28, isSelected: false },
        { name: "Botswana", value: 29, isSelected: false },
        { name: "Bouvet Island", value: 30, isSelected: false },
        { name: "Brasil", value: 31, isSelected: true },
        { name: "British Indian Ocean Territory (the)", value: 32, isSelected: false },
        { name: "Brunei Darussalam", value: 33, isSelected: false },
        { name: "Bulgaria", value: 34, isSelected: false },
        { name: "Burkina Faso", value: 35, isSelected: false },
        { name: "Burundi", value: 36, isSelected: false },
        { name: "Cabo Verde", value: 37, isSelected: false },
        { name: "Cambodia", value: 38, isSelected: false },
        { name: "Cameroon", value: 39, isSelected: false },
        { name: "Canada", value: 40, isSelected: false },
        { name: "Cayman Islands (the)", value: 41, isSelected: false },
        { name: "Central African Republic (the)", value: 42, isSelected: false },
        { name: "Chad", value: 43, isSelected: false },
        { name: "Chile", value: 44, isSelected: false },
        { name: "China", value: 45, isSelected: false },
        { name: "Christmas Island", value: 46, isSelected: false },
        { name: "Cocos (Keeling) Islands (the)", value: 47, isSelected: false },
        { name: "Colombia", value: 48, isSelected: false },
        { name: "Comoros (the)", value: 49, isSelected: false },
        { name: "Congo (the Democratic Republic of the)", value: 50, isSelected: false },
        { name: "Congo (the)", value: 51, isSelected: false },
        { name: "Cook Islands (the)", value: 52, isSelected: false },
        { name: "Costa Rica", value: 53, isSelected: false },
        { name: "Croatia", value: 54, isSelected: false },
        { name: "Cuba", value: 55, isSelected: false },
        { name: "Curaçao", value: 56, isSelected: false },
        { name: "Cyprus", value: 57, isSelected: false },
        { name: "Czechia", value: 58, isSelected: false },
        { name: "Côte d'Ivoire", value: 59, isSelected: false },
        { name: "Denmark", value: 60, isSelected: false },
        { name: "Djibouti", value: 61, isSelected: false },
        { name: "Dominica", value: 62, isSelected: false },
        { name: "Dominican Republic (the)", value: 63, isSelected: false },
        { name: "Ecuador", value: 64, isSelected: false },
        { name: "Egypt", value: 65, isSelected: false },
        { name: "El Salvador", value: 66, isSelected: false },
        { name: "Equatorial Guinea", value: 67, isSelected: false },
        { name: "Eritrea", value: 68, isSelected: false },
        { name: "Estonia", value: 69, isSelected: false },
        { name: "Eswatini", value: 70, isSelected: false },
        { name: "Ethiopia", value: 71, isSelected: false },
        { name: "Falkland Islands (the) [Malvinas]", value: 72, isSelected: false },
        { name: "Faroe Islands (the)", value: 73, isSelected: false },
        { name: "Fiji", value: 74, isSelected: false },
        { name: "Finland", value: 75, isSelected: false },
        { name: "France", value: 76, isSelected: false },
        { name: "French Guiana", value: 77, isSelected: false },
        { name: "French Polynesia", value: 78, isSelected: false },
        { name: "French Southern Territories (the)", value: 79, isSelected: false },
        { name: "Gabon", value: 80, isSelected: false },
        { name: "Gambia (the)", value: 81, isSelected: false },
        { name: "Georgia", value: 82, isSelected: false },
        { name: "Germany", value: 83, isSelected: false },
        { name: "Ghana", value: 84, isSelected: false },
        { name: "Gibraltar", value: 85, isSelected: false },
        { name: "Greece", value: 86, isSelected: false },
        { name: "Greenland", value: 87, isSelected: false },
        { name: "Grenada", value: 88, isSelected: false },
        { name: "Guadeloupe", value: 89, isSelected: false },
        { name: "Guam", value: 90, isSelected: false },
        { name: "Guatemala", value: 91, isSelected: false },
        { name: "Guernsey", value: 92, isSelected: false },
        { name: "Guinea", value: 93, isSelected: false },
        { name: "Guinea-Bissau", value: 94, isSelected: false },
        { name: "Guyana", value: 95, isSelected: false },
        { name: "Haiti", value: 96, isSelected: false },
        { name: "Heard Island and McDonald Islands", value: 97, isSelected: false },
        { name: "Holy See (the)", value: 98, isSelected: false },
        { name: "Honduras", value: 99, isSelected: false },
        { name: "Hong Kong", value: 100, isSelected: false },
        { name: "Hungary", value: 101, isSelected: false },
        { name: "Iceland", value: 102, isSelected: false },
        { name: "India", value: 103, isSelected: false },
        { name: "Indonesia", value: 104, isSelected: false },
        { name: "Iran (Islamic Republic of)", value: 105, isSelected: false },
        { name: "Iraq", value: 106, isSelected: false },
        { name: "Ireland", value: 107, isSelected: false },
        { name: "Isle of Man", value: 108, isSelected: false },
        { name: "Israel", value: 109, isSelected: false },
        { name: "Italy", value: 110, isSelected: false },
        { name: "Jamaica", value: 111, isSelected: false },
        { name: "Japan", value: 112, isSelected: false },
        { name: "Jersey", value: 113, isSelected: false },
        { name: "Jordan", value: 114, isSelected: false },
        { name: "Kazakhstan", value: 115, isSelected: false },
        { name: "Kenya", value: 116, isSelected: false },
        { name: "Kiribati", value: 117, isSelected: false },
        { name: "Korea (the Democratic People's Republic of)", value: 118, isSelected: false },
        { name: "Korea (the Republic of)", value: 119, isSelected: false },
        { name: "Kuwait", value: 120, isSelected: false },
        { name: "Kyrgyzstan", value: 121, isSelected: false },
        { name: "Lao People's Democratic Republic (the)", value: 122, isSelected: false },
        { name: "Latvia", value: 123, isSelected: false },
        { name: "Lebanon", value: 124, isSelected: false },
        { name: "Lesotho", value: 125, isSelected: false },
        { name: "Liberia", value: 126, isSelected: false },
        { name: "Libya", value: 127, isSelected: false },
        { name: "Liechtenstein", value: 128, isSelected: false },
        { name: "Lithuania", value: 129, isSelected: false },
        { name: "Luxembourg", value: 130, isSelected: false },
        { name: "Macao", value: 131, isSelected: false },
        { name: "Madagascar", value: 132, isSelected: false },
        { name: "Malawi", value: 133, isSelected: false },
        { name: "Malaysia", value: 134, isSelected: false },
        { name: "Maldives", value: 135, isSelected: false },
        { name: "Mali", value: 136, isSelected: false },
        { name: "Malta", value: 137, isSelected: false },
        { name: "Marshall Islands (the)", value: 138, isSelected: false },
        { name: "Martinique", value: 139, isSelected: false },
        { name: "Mauritania", value: 140, isSelected: false },
        { name: "Mauritius", value: 141, isSelected: false },
        { name: "Mayotte", value: 142, isSelected: false },
        { name: "Mexico", value: 143, isSelected: false },
        { name: "Micronesia (Federated States of)", value: 144, isSelected: false },
        { name: "Moldova (the Republic of)", value: 145, isSelected: false },
        { name: "Monaco", value: 146, isSelected: false },
        { name: "Mongolia", value: 147, isSelected: false },
        { name: "Montenegro", value: 148, isSelected: false },
        { name: "Montserrat", value: 149, isSelected: false },
        { name: "Morocco", value: 150, isSelected: false },
        { name: "Mozambique", value: 151, isSelected: false },
        { name: "Myanmar", value: 152, isSelected: false },
        { name: "Namibia", value: 153, isSelected: false },
        { name: "Nauru", value: 154, isSelected: false },
        { name: "Nepal", value: 155, isSelected: false },
        { name: "Netherlands (the)", value: 156, isSelected: false },
        { name: "New Caledonia", value: 157, isSelected: false },
        { name: "New Zealand", value: 158, isSelected: false },
        { name: "Nicaragua", value: 159, isSelected: false },
        { name: "Niger (the)", value: 160, isSelected: false },
        { name: "Nigeria", value: 161, isSelected: false },
        { name: "Niue", value: 162, isSelected: false },
        { name: "Norfolk Island", value: 163, isSelected: false },
        { name: "Northern Mariana Islands (the)", value: 164, isSelected: false },
        { name: "Norway", value: 165, isSelected: false },
        { name: "Oman", value: 166, isSelected: false },
        { name: "Pakistan", value: 167, isSelected: false },
        { name: "Palau", value: 168, isSelected: false },
        { name: "Palestine, State of", value: 169, isSelected: false },
        { name: "Panama", value: 170, isSelected: false },
        { name: "Papua New Guinea", value: 171, isSelected: false },
        { name: "Paraguay", value: 172, isSelected: false },
        { name: "Peru", value: 173, isSelected: false },
        { name: "Philippines (the)", value: 174, isSelected: false },
        { name: "Pitcairn", value: 175, isSelected: false },
        { name: "Poland", value: 176, isSelected: false },
        { name: "Portugal", value: 177, isSelected: false },
        { name: "Puerto Rico", value: 178, isSelected: false },
        { name: "Qatar", value: 179, isSelected: false },
        { name: "Republic of North Macedonia", value: 180, isSelected: false },
        { name: "Romania", value: 181, isSelected: false },
        { name: "Russian Federation (the)", value: 182, isSelected: false },
        { name: "Rwanda", value: 183, isSelected: false },
        { name: "Réunion", value: 184, isSelected: false },
        { name: "Saint Barthélemy", value: 185, isSelected: false },
        { name: "Saint Helena, Ascension and Tristan da Cunha", value: 186, isSelected: false },
        { name: "Saint Kitts and Nevis", value: 187, isSelected: false },
        { name: "Saint Lucia", value: 188, isSelected: false },
        { name: "Saint Martin (French part)", value: 189, isSelected: false },
        { name: "Saint Pierre and Miquelon", value: 190, isSelected: false },
        { name: "Saint Vincent and the Grenadines", value: 191, isSelected: false },
        { name: "Samoa", value: 192, isSelected: false },
        { name: "San Marino", value: 193, isSelected: false },
        { name: "Sao Tome and Principe", value: 194, isSelected: false },
        { name: "Saudi Arabia", value: 195, isSelected: false },
        { name: "Senegal", value: 196, isSelected: false },
        { name: "Serbia", value: 197, isSelected: false },
        { name: "Seychelles", value: 198, isSelected: false },
        { name: "Sierra Leone", value: 199, isSelected: false },
        { name: "Singapore", value: 200, isSelected: false },
        { name: "Sint Maarten (Dutch part)", value: 201, isSelected: false },
        { name: "Slovakia", value: 202, isSelected: false },
        { name: "Slovenia", value: 203, isSelected: false },
        { name: "Solomon Islands", value: 204, isSelected: false },
        { name: "Somalia", value: 205, isSelected: false },
        { name: "South Africa", value: 206, isSelected: false },
        { name: "South Georgia and the South Sandwich Islands", value: 207, isSelected: false },
        { name: "South Sudan", value: 208, isSelected: false },
        { name: "Spain", value: 209, isSelected: false },
        { name: "Sri Lanka", value: 210, isSelected: false },
        { name: "Sudan (the)", value: 211, isSelected: false },
        { name: "Suriname", value: 212, isSelected: false },
        { name: "Svalbard and Jan Mayen", value: 213, isSelected: false },
        { name: "Sweden", value: 214, isSelected: false },
        { name: "Switzerland", value: 215, isSelected: false },
        { name: "Syrian Arab Republic", value: 216, isSelected: false },
        { name: "Taiwan", value: 217, isSelected: false },
        { name: "Tajikistan", value: 218, isSelected: false },
        { name: "Tanzania, United Republic of", value: 219, isSelected: false },
        { name: "Thailand", value: 220, isSelected: false },
        { name: "Timor-Leste", value: 221, isSelected: false },
        { name: "Togo", value: 222, isSelected: false },
        { name: "Tokelau", value: 223, isSelected: false },
        { name: "Tonga", value: 224, isSelected: false },
        { name: "Trinidad and Tobago", value: 225, isSelected: false },
        { name: "Tunisia", value: 226, isSelected: false },
        { name: "Turkey", value: 227, isSelected: false },
        { name: "Turkmenistan", value: 228, isSelected: false },
        { name: "Turks and Caicos Islands (the)", value: 229, isSelected: false },
        { name: "Tuvalu", value: 230, isSelected: false },
        { name: "Uganda", value: 231, isSelected: false },
        { name: "Ukraine", value: 232, isSelected: false },
        { name: "United Arab Emirates (the)", value: 233, isSelected: false },
        { name: "United Kingdom of Great Britain and Northern Ireland (the)", value: 234, isSelected: false },
        { name: "United States Minor Outlying Islands (the)", value: 235, isSelected: false },
        { name: "United States of America (the)", value: 236, isSelected: false },
        { name: "Uruguay", value: 237, isSelected: false },
        { name: "Uzbekistan", value: 238, isSelected: false },
        { name: "Vanuatu", value: 239, isSelected: false },
        { name: "Venezuela (Bolivarian Republic of)", value: 240, isSelected: false },
        { name: "Viet Nam", value: 241, isSelected: false },
        { name: "Virgin Islands (British)", value: 242, isSelected: false },
        { name: "Virgin Islands (U.S.)", value: 243, isSelected: false },
        { name: "Wallis and Futuna", value: 244, isSelected: false },
        { name: "Western Sahara", value: 245, isSelected: false },
        { name: "Yemen", value: 246, isSelected: false },
        { name: "Zambia", value: 247, isSelected: false },
        { name: "Zimbabwe", value: 248, isSelected: false },
        { name: "Åland Islands", value: 249, isSelected: false }
      ]
};
